services:
  # INSTAChat Realtime Backend Service
  - type: web
    name: instachat-hcs
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: "https://instachat07.netlify.app"
